djAerolith/djaerolith/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path, include

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from registration.backends.simple.views import RegistrationView

from registration_app.forms import get_registration_form

from views import (
    health,
    login_error,
    new_social_user,
    js_error,
    test_500,
    healthz,
    trigger500,
    jwt_req,
    jwt_extend,
    slow_view,
    paypal_ipn,
)
from accounts.views import social, username_change
from base.views import listmanager


class AerolithRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return "/"


urlpatterns = [
    # Example:
    # (r'^djAerolith/', include('djAerolith.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r"^$", TemplateView.as_view(template_name="base.html")),
    re_path(r"^paypal-ipn", paypal_ipn),
    re_path(r"^old/", TemplateView.as_view(template_name="oldsite/index.html")),
    re_path(r"^health/", health),
    re_path(r"^jwt", jwt_req),
    re_path(r"^jwt_extend", jwt_extend),
    re_path(r"^heymanslowdown/", slow_view),
    re_path(r"^bigfatphony/", trigger500),
    re_path(r"^about/", TemplateView.as_view(template_name="about.html")),
    re_path(r"^privacy/", TemplateView.as_view(template_name="privacy.html")),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/social/$", social),
    re_path(r"^accounts/profile/", include("accounts.urls")),
    re_path(
        r"^accounts/register/$",
        AerolithRegistrationView.as_view(
            form_class=get_registration_form(settings.USE_CAPTCHA)
        ),
    ),
    # override the default registration urls
    re_path(r"^accounts/password/change/$", auth_views.PasswordChangeView.as_view()),
    re_path(
        r"^accounts/password/change/done/$",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    re_path(r"^accounts/password/reset/$", auth_views.PasswordResetView.as_view()),
    re_path(
        r"^accounts/password/reset/done/$",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^accounts/password/reset/complete/$",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    re_path(
        r"^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-" "(?P<token>.+)/$",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^accounts/username/change/$", username_change, name="accounts_edit_username"
    ),
    re_path(
        r"^accounts/username/change/done/$",
        TemplateView.as_view(template_name="accounts/edit_username_done.html"),
    ),
    re_path("", include("social_django.urls", namespace="social")),
    re_path(r"^login_error/", login_error),
    re_path(r"^new_users/", new_social_user),
    re_path(r"^accounts/", include("registration.backends.simple.urls")),
    re_path(r"^listmanager/", listmanager),
    re_path(r"^supporter/", TemplateView.as_view(template_name="support.html")),
    re_path(r"^wordwalls/", include("wordwalls.urls")),
    re_path(r"^flashcards/", include("whitleyCards.urls")),
    re_path(r"^cards/", include("flashcards.urls")),
    re_path(r"^base/", include("base.urls")),
    re_path(r"^js_errors/", js_error),
    re_path(r"^500tester/", test_500),
    re_path(r"^healthz/", healthz),
    re_path(r"^fb_recover/", TemplateView.as_view(template_name="fb_recover.html")),
]

urlpatterns += staticfiles_urlpatterns()  # for static serving, only works
# if DEBUG is true

djAerolith/flashcards/urls.py
from django.urls import re_path

from flashcards.views import main, new_quiz, add_to_wordvault

urlpatterns = [
    re_path(r"^$", main),
    re_path(r"^api/new_quiz$", new_quiz),
    re_path(r"^api/add_to_wordvault$", add_to_wordvault),
]

djAerolith/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

import gargoyle
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
#from registration.forms import RegistrationFormUniqueEmail
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from registration_app.forms import get_registration_form
from registration.backends.simple.views import RegistrationView

from views import (health, login_error, new_social_user, js_error, test_500,
                   healthz, trigger500, jwt_req)
from accounts.views import social, username_change
from base.views import listmanager
gargoyle.autodiscover()


class AerolithRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return "/"


urlpatterns = [
    # Example:
    # (r'^djAerolith/', include('djAerolith.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^old/', TemplateView.as_view(template_name='oldsite/index.html')),
    url(r'^health/', health),
    url(r'^jwt/', jwt_req),
    url(r'^bigfatphony/', trigger500),
    url(r'^about/', TemplateView.as_view(template_name='about.html')),
    url(r'^privacy/', TemplateView.as_view(template_name='privacy.html')),
    url(r'^tos/', TemplateView.as_view(template_name='tos.html')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/social/$', social),
    url(r'^accounts/profile/', include('accounts.urls')),
    url(r'^accounts/register/$', AerolithRegistrationView.as_view(
        form_class=get_registration_form(settings.DEBUG))),

    #override the default registration urls
    url(r'^accounts/password/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^accounts/password/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^accounts/password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-'
        '(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),

    url(r'^accounts/username/change/$', username_change,
        name='accounts_edit_username'),

    url(r'^accounts/username/change/done/$',
        TemplateView.as_view(template_name='accounts/edit_username_done.html')
        ),
    url('', include('social_django.urls', namespace='social')),
    url(r'^login_error/', login_error),
    url(r'^new_users/', new_social_user),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^listmanager/', listmanager),
    url(r'^supporter/', TemplateView.as_view(template_name='support.html')),
    url(r'^wordwalls/', include('wordwalls.urls')),
    url(r'^flashcards/', include('whitleyCards.urls')),
    url(r'^cards/', include('flashcards.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^js_errors/', js_error),
    url(r'^500tester/', test_500),
    url(r'^healthz/', healthz)
]

urlpatterns += staticfiles_urlpatterns()    # for static serving, only works
                                            # if DEBUG is true

djAerolith/wordwalls/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

from django.urls import re_path, include

from wordwalls.views import table, mark_missed, ajax_upload, log
from wordwalls.rpc import table_rpc
from wordwalls.stats import leaderboard, get_medals, main, get_stats


urlpatterns = [
    re_path(r"^$", table),
    re_path(r"^table/(?P<tableid>\d+)/$", table, name="wordwalls_table"),
    re_path(r"^table/(?P<tableid>\d+)/rpc/$", table_rpc),
    re_path(r"^table/(?P<tableid>\d+)/missed/$", mark_missed),
    re_path(r"^ajax_upload/$", ajax_upload, name="ajax_upload"),
    re_path(r"^api/", include("wordwalls.api_urls")),
    # re_path(r'^getNewSignature/$', 'wordwalls.views.get_new_signature',
    # name='get_new_signature')
    re_path(r"^leaderboard/$", leaderboard),
    re_path(r"^leaderboard/getboard/$", get_medals),
    re_path(r"^stats/$", main),
    re_path(r"^stats/api/(?P<lexicon>\d+)/(?P<type_of_challenge_id>\d+)/$", get_stats),
    re_path(r"^log/$", log),
]

djAerolith/base/forms.py
# Forms that are global to a few different apps: wordwalls, flashcards,
# whitleyCards for example.
from django import forms
from base.models import Lexicon, WordList, EXCLUDED_LEXICA
from wordwalls.models import NamedList
from django.utils.translation import gettext_lazy as _


class LexiconForm(forms.Form):
    lexicon = forms.ModelChoiceField(
        queryset=Lexicon.objects.exclude(lexiconName__in=EXCLUDED_LEXICA),
        label="Lexicon",
        widget=forms.Select(attrs={"class": "form-control"}),
        empty_label=None,
    )


class NumQuestionsForm(forms.Form):
    num_questions = forms.IntegerField(
        max_value=200,
        min_value=20,
        initial=50,
        required=False,
        widget=forms.NumberInput(attrs={"class": "form-control"}),
    )


class UserListForm(forms.Form):
    file = forms.FileField(label="File")


class WordListChoiceField(forms.ModelChoiceField):
    def to_python(self, value):
        """Normalize the choice field to an actual SavedList"""
        if not value:
            return None

        try:
            sl = WordList.objects.get(pk=value)
        except WordList.DoesNotExist:
            return None
        return sl


class SavedListForm(forms.Form):
    CONTINUE_LIST_CHOICE = 1
    FIRST_MISSED_CHOICE = 2
    RESTART_LIST_CHOICE = 3
    listOptions = (
        (CONTINUE_LIST_CHOICE, _("Continue list")),
        (FIRST_MISSED_CHOICE, _("Quiz on first missed")),
        (RESTART_LIST_CHOICE, _("Restart list")),
    )

    listOption = forms.TypedChoiceField(
        choices=listOptions,
        label="Quiz options",
        widget=forms.Select(attrs={"class": "form-control"}),
        coerce=int,
    )

    wordList = WordListChoiceField(
        label="List choice",
        queryset=WordList.objects.none(),
        widget=forms.Select(attrs={"size": "10", "class": "form-control"}),
    )


class NamedListChoiceField(forms.ModelChoiceField):
    def to_python(self, value):
        if not value:
            return None

        try:
            nl = NamedList.objects.get(pk=value)
        except NamedList.DoesNotExist:
            return None
        return nl


class NamedListForm(forms.Form):
    namedList = NamedListChoiceField(
        label="List choice",
        queryset=NamedList.objects.none(),
        widget=forms.Select(attrs={"size": "15", "class": "form-control"}),
    )

djAerolith/flashcards/views.py
import logging
import json

from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.conf import settings

from base.models import Lexicon, WordList
from base.utils import generate_question_map, quizzes_response
from lib.auth import create_jwt
from lib.response import response
from lib.wdb_interface.wdb_helper import (
    word_search,
    add_to_wordvault as wdb_add_to_wordvault,
)
from lib.wdb_interface.exceptions import WDBError
from lib.wdb_interface.word_searches import temporary_list_name
from wordwalls.api import build_search_criteria
from wordwalls.game import GameInitException

logger = logging.getLogger(__name__)


@login_required
def main(request):
    quizzes = WordList.objects.filter(user=request.user, is_temporary=False)
    return render(
        request,
        "flashcards/index.html",
        {
            "numCards": 0,
            "savedLists": json.dumps(quizzes_response(quizzes)),
            "STATIC_SRV": (
                settings.WEBPACK_DEV_SERVER_URL
                if (settings.USE_WEBPACK_DEV_SERVER and settings.DEBUG)
                else ""
            ),
        },
    )


@login_required
def new_quiz(request):
    """
    Create a new quiz but doesn't create any 'card' models.
    Card models will only be used for cardbox in future.
    """
    body = json.loads(request.body)
    logger.debug(body)
    lexicon = Lexicon.objects.get(lexiconName=body["lexicon"])
    try:
        search_description = build_search_criteria(
            request.user, lexicon, body["searchCriteria"]
        )
    except GameInitException as e:
        return response(str(e), status=400)

    questions = word_search(search_description, expand=True)
    if questions.size() == 0:
        return response("No questions were found.", status=400)
    wl = WordList()
    wl.initialize_list(
        list(questions.to_python()), lexicon, None, shuffle=True, save=False
    )
    q_map = generate_question_map(questions)
    quiz_name = temporary_list_name(search_description, lexicon.lexiconName)
    # XXX add 1000-question limit?
    return response(
        {
            "list": wl.to_python(),
            "q_map": q_map,
            "quiz_name": quiz_name,
        }
    )


@login_required
def add_to_wordvault(request):
    body = json.loads(request.body)
    logger.debug(body)
    lexicon = Lexicon.objects.get(lexiconName=body["lexicon"])
    try:
        search_description = build_search_criteria(
            request.user, lexicon, body["searchCriteria"]
        )
    except GameInitException as e:
        return response(str(e), status=400)

    try:
        questions = word_search(search_description, expand=False)
    except WDBError as e:
        return response(str(e), status=400)
    if questions.size() == 0:
        return response("No questions were found.", status=400)

    # Shuffle before adding to avoid things like alphabetical order.
    questions.shuffle()
    alphagrams = questions.alphagram_string_list()
    token = create_jwt(request.user)
    try:
        num_added = wdb_add_to_wordvault(alphagrams, lexicon.lexiconName, token)
    except Exception as e:
        return response(str(e), status=400)

    return response({"msg": f"{num_added} cards were added"})

djAerolith/flashcards/templates/flashcards/card_help.html
<P>Aerolith Flashcards was primarily written to be used with a poor or non-existent Internet connection, for example, for studying on public transportation / planes / walking down the street. </P>
<h4>How to use it</h4>
<ul>
    <li>Create a quiz by clicking New Quiz. This brings up probability search parameters (and maybe more in the future). As of right now, the biggest the quiz can be is 1000 alphagrams. This is the only step that requires having an Internet connection.</li>
    <li>The entire quiz is loaded on your computer or device. You can click Correct / Missed or go back cards. Clicking Missed will ask you the question again once you've gone through the entire set of cards. If you keep missing it the question will keep coming up at the end of the current set, much like in Wordwalls.</li>
    <li>The current state of the quiz is saved locally on your computer or device after each question. <strong>Only one quiz can be saved locally at a time.</strong> This is good for tablets where you can switch between different apps. For example, if you have Internet and you refresh the page, you will automatically continue from where you left off.</li>
    <li>You can back up your current local progress with the Aerolith server by clicking the Sync button at any time (when your Internet comes back, for example). This will make a copy remotely so that you can continue the quiz later on another device, for example, or allow you to quiz on only your first-missed questions.</li>
    <li>When you come back to this page later, you have a choice between continuing your local quiz or one of the remote quizzes. Note that loading a remote quiz will wipe out the progress on your local quiz -- the local quiz is replaced by the remote quiz. You will still have to click Sync to continue updating the remote quiz.</li>
</ul>
<h4>Local quizzes? Remote quizzes?</h4>
<P>This is explained above but if it is too much text here is the simple explanation. You can only have one local quiz, and it is <em>automatically</em> saved on your computer/device after each question. </P>

<P>You can back it up remotely so that you can quiz on only those words you missed on that quiz later, for example. This is done by clicking Sync whenever you want to back the quiz up. The remote quizzes show you all your quizzes saved on the Aerolith servers. These include the Wordwalls quizzes as well!</P>

djAerolith/flashcards/templates/flashcards/cardbox.html
{% extends "base.html" %}
{% load assets %}
{% block title %}Aerolith Cardbox{% endblock %}

{% block ss %}
    {% assets "css_fileuploader" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}

    {% assets "base_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}

    {% assets "jquery_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock ss %}

{% block content %}

{% assets "js_cardbox" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
<div>
    {{lexForm.as_p}}
</div>

<p>Welcome, {{user}}!</p>


{% if questionCount == 0 %}
<P>You seem to not have any questions saved. You can either upload a Zyzzyva
cardbox file, or start one from scratch.</p>

<div id="accordion">
    <h3><a href="#">Start from Scratch</a></h3>
    <div>
        <p>
        Do a probability search
        </p>
    </div>

    <h3><a href="#">File upload</a></h3>
    <div>
       <p>File upload instructions:</p>
            <ul><li>Select the lexicon for the cardbox you wish to upload.
                </li>
                <li>Determine your Zyzzyva data directory. Simply open up Zyzzyva, open its
                preferences, and copy the Location under "Data Directory".</li>
                <li>Navigate to that location with the file upload tool, then go into the
                    quiz/data/ directory and select the proper directory for your lexicon.
                <li>Go into your lexicon directory and select the file named Anagrams.db</li>
                <li>Click "Open" and please wait a few seconds while we generate your
                    Aerolith cardbox from your Zyzzyva data.</li></ul>
            <div id="file-uploader">
                <noscript>
                    <p>Please enable JavaScript to use file uploader.</p>
                </noscript>
            </div>
            <div id="file-upload-msgs">
            </div>

        </p>
    </div>

</div>

{% else %}

{% endif %}

<script>
$(function() {
    $("#accordion").accordion({autoheight: false,
                               collapsible: true,
                               fillspace: true});

    var uploader = new qq.FileUploader( {
         action: "{% url ajax_upload %}",
         element: $('#file-uploader')[0],
         multiple: false,
         onComplete: function( id, fileName, responseJSON ) {
           if( responseJSON.success )
            {
                $("#file-upload-msgs").text("Success! " + responseJSON.msg);
            }
           else
             {
             }
         },
         onAllComplete: function( uploads ) {
           // uploads is an array of maps
           // the maps look like this: { file: FileObject, response: JSONServerResponse }

         },
         onSubmit: function()
         {
             uploader.setParams({
                // 'lexicon': $("#id_lexicon").val(),
                'csrf_token': '{{ csrf_token }}',
                'csrf_name': 'csrfmiddlewaretoken',
                'csrf_xname': 'X-CSRFToken'
             });
         },
         params: {

         },
       });
});
</script>

{% endblock %}

djAerolith/flashcards/templates/flashcards/ikm.html
{% extends "base.html" %}
{% load assets %}
{% block title %}Aerolith IKM{% endblock %}

{% block ss %}
    {% assets "base_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}

    {% assets "jquery_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}

    {% assets "ikm_css" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock ss %}

{% block content %}

{% assets "js_ikm_quiz" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}

<p>Welcome, {{user}}!</p>

<script type="text/javascript">
    $(function(){
        IKMQuizApp.init({{ikmRunList|safe}});
    });
</script>

<div id="mainDiv">
    <div id="errorMsg"></div>
    <p>You can select a previous IKM run...</p>
    <div id="runList"></div>
    <div style="clear: both; padding-top: 20px;">
        <p>Or, add a new run:</p>
        <select id="wordList">
            <option value="owl2_6s">OWL2 6s</option>
            <option value="owl2_7s">OWL2 7s</option>
            <option value="owl2_8s">OWL2 8s</option>
            <option value="csw12_6s">CSW12 6s</option>
            <option value="csw12_7s">CSW12 7s</option>
            <option value="csw12_8s">CSW12 8s</option>
        </select>
        <button id="listStart">Select</button>
    </div>

</div>

<div id="quizDiv">
    <div id="cardList"></div>
</div>


{# ICANHAZ TEMPLATES #}
{# need verbatim tag so that Django doesn't render Mustache's curly braces #}

{% load verbatim %}
{% verbatim %}

    <script id="runTemplate" type="text/html">
        <div class="run">
            <div class="description">{{description}}</div>
            <div class="lexicon">{{lexicon}}</div>
            <div class="progress">{{qindex}} / {{totalQs}}</div>
            <div class="startDate">Started on: {{started}}</div>
            <div class="lastSaved">Last saved: {{lastSeen}}</div>
            <button class="continueRun">Continue</button>
            <button class="deleteRun">Delete</button>
        </div>
    </script>

    <script id="ikmQuizTemplate" type="text/html">
        <div class="timer"></div>
        <div class="flashcardQ">
            <div class="question">{{question}}</div>
            <div class="answers">
            {{#answers}}
            <div class="answer">{{answer}}</div>
            <div class="definition">{{definition}}</div>
            {{/answers}}
            </div>
        </div>
        <div class="buttonbox">
        <button class="answerButton" id="answer1">Got it</button>
        <button class="answerButton" id="answer2">Almost</button>
        <button class="answerButton" id="answer3">Missed it</button>
        </div>
        <button class="goBack">Go Back</button>
    </script>

{% endverbatim %}

{% endblock %}

djAerolith/flashcards/templates/flashcards/whitleyQuiz.html
{% extends "base.html" %}

{% block content %}

{% load assets %}

{% block addlCSS %}
    {% assets "css_whitley_quiz" %}
        <link href="{{ ASSET_URL }}" rel="stylesheet" type="text/css">
    {% endassets %}
{% endblock %}

{% assets "js_whitley_quiz" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
<p style="color:gray">Flashcards programmed by David Whitley and adapted by Cesar Del Solar, based on code at Ottawa Scrabble Club website by Chris Ten Den</p>
<div>
    <div id="messages"></div>
    <form name="game" onSubmit="solve(); return false;">
        <font face="verdana" style="font-size:15px;">
            <input type="text" name="word">
            <input type="button" onClick="completeSolve();" value="Solve">
            <input type="button" onClick="forceReveal();" value="Hint">
            <input type="button" onClick="toggleHints();" value="Auto">
            <br/>
            <input type="button" onClick="changeSpeed(-1);" value="-">
            <input type="button" onClick="changeSpeed(1);" value="+">
            <span id="speed"><font color='gray'>5 |||||</font></span>
        </font>
    </form>
    <span id="question" style="font-family:'scramble','Lucida Console',monospace; font-size:36px; height:36px;"></span>
    <div id="progress" style="font-family:'verdana'; font-size:15px; height:20px; color:gray">&nbsp;</div>
    <div id="hints" style="font-family:'scramble','Lucida Console',monospace; font-size:36px;height:40px;"></div>
    <div id="variants" style="font-family:'scramble','Lucida Console',monospace; font-size:24px; min-height:25px;"></div>
    <div id="trace"></div>
    <div id="solved"></div>

</div>
<script type="text/javascript">
$(document).ready(function() {
    initializeQuiz("{{ request.get_full_path }}");
    mixpanel.track('Entered flashcards page');
});
</script>
{% endblock content %}