djAerolith/accounts/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

from django.urls import path, re_path
from accounts.views import (
    editProfile,
    viewProfile,
    set_default_lexicon,
    default_lexicon,
    wordvault_settings,
)

urlpatterns = [
    re_path(r"^$", editProfile, name="accounts_edit_profile"),
    path(r"set_default_lexicon/", set_default_lexicon),
    path(r"default_lexicon", default_lexicon),
    path(r"<str:username>/", viewProfile, name="accounts_view_profile"),
    path(r"wordvault_settings", wordvault_settings),
]

djAerolith/djaerolith/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import re_path, include

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from registration.backends.simple.views import RegistrationView

from registration_app.forms import get_registration_form

from views import (
    health,
    login_error,
    new_social_user,
    js_error,
    test_500,
    healthz,
    trigger500,
    jwt_req,
    jwt_extend,
    slow_view,
    paypal_ipn,
)
from accounts.views import social, username_change
from base.views import listmanager


class AerolithRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return "/"


urlpatterns = [
    # Example:
    # (r'^djAerolith/', include('djAerolith.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    re_path(r"^$", TemplateView.as_view(template_name="base.html")),
    re_path(r"^paypal-ipn", paypal_ipn),
    re_path(r"^old/", TemplateView.as_view(template_name="oldsite/index.html")),
    re_path(r"^health/", health),
    re_path(r"^jwt", jwt_req),
    re_path(r"^jwt_extend", jwt_extend),
    re_path(r"^heymanslowdown/", slow_view),
    re_path(r"^bigfatphony/", trigger500),
    re_path(r"^about/", TemplateView.as_view(template_name="about.html")),
    re_path(r"^privacy/", TemplateView.as_view(template_name="privacy.html")),
    re_path(r"^admin/", admin.site.urls),
    re_path(r"^accounts/social/$", social),
    re_path(r"^accounts/profile/", include("accounts.urls")),
    re_path(
        r"^accounts/register/$",
        AerolithRegistrationView.as_view(
            form_class=get_registration_form(settings.USE_CAPTCHA)
        ),
    ),
    # override the default registration urls
    re_path(r"^accounts/password/change/$", auth_views.PasswordChangeView.as_view()),
    re_path(
        r"^accounts/password/change/done/$",
        auth_views.PasswordChangeDoneView.as_view(),
        name="password_change_done",
    ),
    re_path(r"^accounts/password/reset/$", auth_views.PasswordResetView.as_view()),
    re_path(
        r"^accounts/password/reset/done/$",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    re_path(
        r"^accounts/password/reset/complete/$",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    re_path(
        r"^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-" "(?P<token>.+)/$",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    re_path(
        r"^accounts/username/change/$", username_change, name="accounts_edit_username"
    ),
    re_path(
        r"^accounts/username/change/done/$",
        TemplateView.as_view(template_name="accounts/edit_username_done.html"),
    ),
    re_path("", include("social_django.urls", namespace="social")),
    re_path(r"^login_error/", login_error),
    re_path(r"^new_users/", new_social_user),
    re_path(r"^accounts/", include("registration.backends.simple.urls")),
    re_path(r"^listmanager/", listmanager),
    re_path(r"^supporter/", TemplateView.as_view(template_name="support.html")),
    re_path(r"^wordwalls/", include("wordwalls.urls")),
    re_path(r"^flashcards/", include("whitleyCards.urls")),
    re_path(r"^cards/", include("flashcards.urls")),
    re_path(r"^base/", include("base.urls")),
    re_path(r"^js_errors/", js_error),
    re_path(r"^500tester/", test_500),
    re_path(r"^healthz/", healthz),
    re_path(r"^fb_recover/", TemplateView.as_view(template_name="fb_recover.html")),
]

urlpatterns += staticfiles_urlpatterns()  # for static serving, only works
# if DEBUG is true

djAerolith/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

import gargoyle
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls import url, include
# Uncomment the next two lines to enable the admin:
from django.contrib import admin
#from registration.forms import RegistrationFormUniqueEmail
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from registration_app.forms import get_registration_form
from registration.backends.simple.views import RegistrationView

from views import (health, login_error, new_social_user, js_error, test_500,
                   healthz, trigger500, jwt_req)
from accounts.views import social, username_change
from base.views import listmanager
gargoyle.autodiscover()


class AerolithRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return "/"


urlpatterns = [
    # Example:
    # (r'^djAerolith/', include('djAerolith.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', TemplateView.as_view(template_name='base.html')),
    url(r'^old/', TemplateView.as_view(template_name='oldsite/index.html')),
    url(r'^health/', health),
    url(r'^jwt/', jwt_req),
    url(r'^bigfatphony/', trigger500),
    url(r'^about/', TemplateView.as_view(template_name='about.html')),
    url(r'^privacy/', TemplateView.as_view(template_name='privacy.html')),
    url(r'^tos/', TemplateView.as_view(template_name='tos.html')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/social/$', social),
    url(r'^accounts/profile/', include('accounts.urls')),
    url(r'^accounts/register/$', AerolithRegistrationView.as_view(
        form_class=get_registration_form(settings.DEBUG))),

    #override the default registration urls
    url(r'^accounts/password/change/$',
        auth_views.password_change,
        name='password_change'),
    url(r'^accounts/password/change/done/$',
        auth_views.password_change_done,
        name='password_change_done'),
    url(r'^accounts/password/reset/$',
        auth_views.password_reset,
        name='password_reset'),
    url(r'^accounts/password/reset/done/$',
        auth_views.password_reset_done,
        name='password_reset_done'),
    url(r'^accounts/password/reset/complete/$',
        auth_views.password_reset_complete,
        name='password_reset_complete'),
    url(r'^accounts/password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-'
        '(?P<token>.+)/$',
        auth_views.password_reset_confirm,
        name='password_reset_confirm'),

    url(r'^accounts/username/change/$', username_change,
        name='accounts_edit_username'),

    url(r'^accounts/username/change/done/$',
        TemplateView.as_view(template_name='accounts/edit_username_done.html')
        ),
    url('', include('social_django.urls', namespace='social')),
    url(r'^login_error/', login_error),
    url(r'^new_users/', new_social_user),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^listmanager/', listmanager),
    url(r'^supporter/', TemplateView.as_view(template_name='support.html')),
    url(r'^wordwalls/', include('wordwalls.urls')),
    url(r'^flashcards/', include('whitleyCards.urls')),
    url(r'^cards/', include('flashcards.urls')),
    url(r'^base/', include('base.urls')),
    url(r'^js_errors/', js_error),
    url(r'^500tester/', test_500),
    url(r'^healthz/', healthz)
]

urlpatterns += staticfiles_urlpatterns()    # for static serving, only works
                                            # if DEBUG is true

djAerolith/wordwalls/urls.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com

from django.urls import re_path, include

from wordwalls.views import table, mark_missed, ajax_upload, log
from wordwalls.rpc import table_rpc
from wordwalls.stats import leaderboard, get_medals, main, get_stats


urlpatterns = [
    re_path(r"^$", table),
    re_path(r"^table/(?P<tableid>\d+)/$", table, name="wordwalls_table"),
    re_path(r"^table/(?P<tableid>\d+)/rpc/$", table_rpc),
    re_path(r"^table/(?P<tableid>\d+)/missed/$", mark_missed),
    re_path(r"^ajax_upload/$", ajax_upload, name="ajax_upload"),
    re_path(r"^api/", include("wordwalls.api_urls")),
    # re_path(r'^getNewSignature/$', 'wordwalls.views.get_new_signature',
    # name='get_new_signature')
    re_path(r"^leaderboard/$", leaderboard),
    re_path(r"^leaderboard/getboard/$", get_medals),
    re_path(r"^stats/$", main),
    re_path(r"^stats/api/(?P<lexicon>\d+)/(?P<type_of_challenge_id>\d+)/$", get_stats),
    re_path(r"^log/$", log),
]

djAerolith/accounts/models.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com
from django.db import models
from django.contrib.auth.models import User
import logging

from django.db.models.signals import post_save

from base.models import Lexicon

logger = logging.getLogger(__name__)


def getLexicon(request=None):
    if not request:
        return Lexicon.objects.get(lexiconName="NWL23")
    elif request.LANGUAGE_CODE == "es":
        return Lexicon.objects.get(lexiconName="FISE2")
    elif request.LANGUAGE_CODE == "pl":
        return Lexicon.objects.get(lexiconName="OSPS51")
    elif request.LANGUAGE_CODE == "de":
        return Lexicon.objects.get(lexiconName="RD29")
    elif request.LANGUAGE_CODE == "fr":
        return Lexicon.objects.get(lexiconName="FRA24")
    return Lexicon.objects.get(lexiconName="NWL23")


class AerolithProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    coins = models.IntegerField(default=0)
    profile = models.CharField(max_length=2000, blank=True)
    rating = models.IntegerField(default=0)

    NONE_MTYPE = 0
    BRONZE_MTYPE = 1
    SILVER_MTYPE = 2
    GOLD_MTYPE = 3

    MEMBERSHIP_TYPES = (
        (NONE_MTYPE, "None"),
        (BRONZE_MTYPE, "Bronze"),
        (SILVER_MTYPE, "Silver"),
        (GOLD_MTYPE, "Gold"),
    )

    member = models.BooleanField(default=False)
    membershipType = models.IntegerField(choices=MEMBERSHIP_TYPES, default=NONE_MTYPE)
    membershipExpiry = models.DateTimeField(null=True, blank=True)

    # specific per game
    customWordwallsStyle = models.CharField(max_length=1000, blank=True)
    wordwallsSaveListSize = models.IntegerField(default=0)

    wordvault_settings = models.TextField(default="{}", blank=True)

    # project-wide
    defaultLexicon = models.ForeignKey(
        Lexicon, default=getLexicon, on_delete=models.SET_DEFAULT
    )
    avatarUrl = models.CharField(null=True, blank=True, max_length=512)
    additional_data = models.TextField(default="{}", blank=True)

    def __str__(self):
        return "Profile for " + self.user.username


def user_registered_handler(sender, **kwargs):
    if kwargs["created"] and not kwargs.get("raw", False):
        profile = AerolithProfile()
        profile.user = kwargs["instance"]
        profile.save()


post_save.connect(user_registered_handler, User)

djAerolith/accounts/forms.py
# Aerolith 2.0: A web-based word game website
# Copyright (C) 2011 Cesar Del Solar
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# To contact the author, please email delsolar at gmail dot com
import re

from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.utils.translation import gettext as _

from base.models import Lexicon, EXCLUDED_LEXICA


class ProfileEditForm(forms.Form):
    lexiconChoices = Lexicon.objects.exclude(lexiconName__in=EXCLUDED_LEXICA)
    defaultLexicon = forms.ModelChoiceField(
        queryset=lexiconChoices,
        label="Default Lexicon",
        widget=forms.Select(attrs={"class": "form-control"}),
        empty_label=None,
    )
    profileText = forms.CharField(
        widget=forms.Textarea(attrs={"class": "form-control"}),
        label="Your profile",
        required=False,
    )
    disableChat = forms.BooleanField(label="Disable Chat", required=False)
    default_language = forms.ChoiceField(
        choices=settings.LANGUAGES,
        required=False,
        widget=forms.Select(attrs={"class": "form-control"}),
    )


class UsernameEditForm(forms.Form):
    username = forms.CharField(label="Your desired username", required=True)

    def clean(self):
        u = self.cleaned_data.get("username")
        if not u:
            raise forms.ValidationError(_("You must enter a username"))
        if not re.match(r"\w+$", u):
            raise forms.ValidationError(
                _("Your username must consist of alphanumeric characters.")
            )
        # Case-insensitive username match
        users = User.objects.filter(username__iexact=u)
        if users.count() > 0:
            raise forms.ValidationError(
                _("This username already exists in our system!")
            )

djAerolith/accounts/templates/accounts/editProfile.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% blocktrans with username=profile.user.username %}Edit {{username}}'s profile{% endblocktrans %}{% endblock %}

{% block content %}
{% if profile.member %}
<div class="row">
You are currently a supporter; your membership expires on {{profile.membershipExpiry|date:"D, M d Y"}}.
</div>
{% else %}

{% endif %}
<form class="form-horizontal" role="form" method="post" action="{% url 'accounts_edit_profile' %}" style="margin-top: 20px;">{% csrf_token %}
  <div class="form-group">
    <label for="input-lexicon" class="col-sm-2 control-label">{% trans "Default Lexicon" %}</label>
    <div class="col-sm-4">
      {{ pForm.defaultLexicon }}
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-1">{% blocktrans %}Enter up to 2000 characters of information about yourself to show on your profile. You may use <a href="http://en.wikipedia.org/wiki/Markdown" target="_blank">Markdown</a>.{% endblocktrans %}</div>
  </div>
  <div class="form-group">
    <label for="input-profile" class="col-sm-2 control-label">{% trans "Your profile"%}:</label>
    <div class="col-sm-10">
      {{ pForm.profileText }}
    </div>
  </div>
<!--   <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <div class="checkbox">
        <label>
          <input type="checkbox" name="disableChat" id="id_disableChat"> {% trans "Disable chat" %}
        </label>
      </div>
    </div>
  </div> -->
  <div class="form-group">
    <label for="input-language" class="col-sm-2 control-label">{% trans "Default Aerolith Interface Language" %}</label>
    <div class="col-sm-4">
      {{ pForm.default_language }}
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">{% trans "Save Profile" %}</button>
    </div>
  </div>
</form>
<p>
    <a href="/accounts/password/change">{% trans "Password change form" %}</a><br><br>
    <a href="/accounts/username/change">{% trans "Username change form" %}</a>
</p>
<script type="text/javascript">
/* global $, JSON*/
  $(document).ready(function() {
    var addlData;
    try {
      addlData = JSON.parse("{{profile.additional_data|escapejs}}");
    } catch (e) {
      addlData = {disableChat: false};
    }
    $("#id_profileText").val("{{profile.profile|escapejs}}");
    $("#id_defaultLexicon option[value='{{profile.defaultLexicon.pk}}']").prop(
        'selected', true);
    $('#id_disableChat').prop('checked', addlData.disableChat);
    $("#id_default_language option[value='{{session_language}}']").prop(
      'selected', true);
  });
  $("#id_profileText").css({'height': '300px', 'width': '500px'});
</script>

{% endblock %}

djAerolith/accounts/templates/accounts/edit_username.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% blocktrans with username=user.username %}Edit {{username}}'s username{% endblocktrans %}{% endblock %}

{% block content %}

<form class="form-horizontal" role="form" method="post" action="{% url 'accounts_edit_username' %}" style="margin-top: 20px;">{% csrf_token %}
    {{u_form.non_field_errors}}
    {{u_form.username.errors}}
  <div class="form-group">
    <label for="input-username" class="col-sm-2 control-label">{% trans "Desired username" %}</label>
    <div class="col-sm-4">
      {{ u_form.username }}
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">{% trans "Edit username" %}</button>
    </div>
  </div>
</form>

{% endblock %}

djAerolith/accounts/templates/accounts/edit_username_done.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}
<title>{% trans "Aerolith - Username updated" %}</title>
{% endblock %}

{% block content %}
<p>{% trans "Your username was changed successfully." %}</p><br>
{% endblock %}

djAerolith/accounts/templates/accounts/preferences.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "Preferences" %}{% endblock %}


{% block content_title %}<H3>{% trans "Preferences" %}</H3>{%endblock%}

{% block content %}
<div class="row">
<h4>{% trans "Associate/Remove Social Media Accounts" %}</h4>
    <div class="social-buttons"></div>
</div>
<div class="row">
<h4>{% trans "Saved List Manager" %}</h4>
<h5>{% trans "You can view and delete your old saved lists here. Be careful, as deleting a saved list is permanent!" %}</h5>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table id="list-table" class="table">
                <thead>
                <tr>
                    <th>{% trans "Name" %}</th>
                    <th>{% trans "Lexicon" %}</th>
                    <th>{% trans "Progress" %}</th>
                    <th>{% trans "Total questions" %}</th>
                    <th>{% trans "Last Saved" %}</th>
                </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
    <button type="button" class="btn btn-danger btn-sm" id="delete-lists">{% trans "Delete Selected Lists" %}</button>
    </div>
</div>
<script>
/* global $, JSON*/
$(function() {
    "use strict";
    var $socialButtons = $('.social-buttons');
    var service, imgUrl, href, assocId, discUrl;
    // backends comes from a context processor
    {% for assoc in backends.associated %}
        {% if assoc.provider == 'facebook' %}
            service = 'Facebook';
            assocId = {{assoc.id}};
            discUrl = '{% url 'social:disconnect_individual' 'facebook' assoc.id %}';
        {% endif %}
        {% if assoc.provider == 'google-oauth2' %}
            service = 'Google';
            assocId = {{assoc.id}};
            discUrl = '{% url 'social:disconnect_individual' 'google-oauth2' assoc.id %}'
        {% endif %}
        $socialButtons.append([
            '<div class="row" style="margin-bottom:10px;">',
            '<div class="col-sm-1">',
            service,
            '</div><div class="col-sm-1">',
            '<form action="', discUrl, '" method="POST">',
            '<input type="hidden" name="csrfmiddlewaretoken" value="',
            '{{csrf_token}}"/>',
            '<button class="btn btn-sm btn-default ',
            'disassoc-{{assoc.provider}}" type="submit">X</button>',
            '</div></div>'
        ].join(''));
    {% endfor %}

    {% for assoc in backends.not_associated %}
        {% if assoc == 'facebook' %}
            imgUrl = "/static/img/aerolith/login_with_facebook.png";
            href = '{% url "social:begin" "facebook" %}';
        {% endif %}
        {% if assoc == 'google-oauth2' %}
            imgUrl = "/static/img/aerolith/login_with_google.png";
            href = '{% url "social:begin" "google-oauth2" %}';
        {% endif %}
        $socialButtons.append([
            '<p><a class="{{assoc}}-btn social-login" href="', href, '">',
            '<img src="', imgUrl, '"></a></p>'
        ].join(''));
    {% endfor %}

    $('.disassoc-facebook').click(function() {
        // alert('should disassociate facebook')

    });

    $('.disassoc-google-oauth2').click(function() {
        alert('should disassociate google')


    });

    function fetchListData() {
        $.get('/base/api/saved_lists/', {
            'temp': 0
        }, function(data) {
            data.lists.sort(function(a, b) {
                if (a.lastSaved > b.lastSaved) {
                    return -1;
                } else if (a.lastSaved < b.lastSaved) {
                    return 1;
                } else {
                    return 0;
                }
            });
            populateTable(data);
        }, 'json');
    }
    /**
     * Populates a table with list data.
     * @param  {Object} data
     */
    function populateTable(data) {
        $('#list-table tbody').empty();
        $.each(data.lists, function(idx, list) {
            var row = $('<tr/>');
            row.append([
                '<td>',
                '<input type="checkbox" class="del-checkbox" data-list-id="',
                list.id, '" style="margin-right:10px;"/> ',
                list.name, '</td>'
            ].join(''));
            row.append([
                '<td>', list.lexicon, '</td>'
            ].join(''));
            row.append([
                '<td>', list.questionIndex, '/', list.numCurAlphagrams, '</td>'
            ].join(''));
            row.append([
                '<td>', list.numAlphagrams, '</td>'
            ].join(''));
            row.append([
                '<td>', list.lastSaved, '</td>'
            ].join(''));

            $('#list-table tbody').append(row);

        });
    }

    $('#delete-lists').click(function() {
        var del, toDelete;
        if ($('.del-checkbox:checked').length > 0) {
            del = window.confirm(
                'Are you sure you wish to permanently delete these lists?');
            if (!del) {
                return;
            }
        }
        toDelete = [];
        $('.del-checkbox:checked').each(function() {
            toDelete.push(parseInt($(this).data('listId'), 10));
        });
        $.ajax({
            url: '/base/api/saved_lists/',
            data: JSON.stringify(toDelete),
            type: 'DELETE',
            success: function() {
                fetchListData();
            },
            dataType: 'json'
        });
    });

    $(document).ajaxSend(function(event, xhr, settings) {
        function getCookie(name) {
          var cookieValue = null;
          if (document.cookie && document.cookie !== '') {
            var cookies = document.cookie.split(';');
            for (var i = 0; i < cookies.length; i++) {
              var cookie = jQuery.trim(cookies[i]);
              // Does this cookie string begin with the name we want?
              if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
              }
            }
          }
          return cookieValue;
        }
        function sameOrigin(url) {
          // url could be relative or scheme relative or absolute
          var host = document.location.host; // host + port
          var protocol = document.location.protocol;
          var sr_origin = '//' + host;
          var origin = protocol + sr_origin;
          // Allow absolute or scheme relative URLs to same origin
          return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
              (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
              // or any other URL that isn't scheme relative or absolute i.e relative.
              !(/^(\/\/|http:|https:).*/.test(url));
        }
        function safeMethod(method) {
          return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        if (!safeMethod(settings.type) && sameOrigin(settings.url)) {
          xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
        }
    });

    fetchListData();
});
</script>
{% endblock %}